Enable passing the image compression probability for the Albumentations library
BSB-Group/yolov5-extended pull request #5
Opened 2024-10-08 16:14 UTC by hichem-sea

## What?

This PR introduces support for passing the image compression probability as a parameter in the Albumentations augmentation library. This allows the user to control the likelihood of applying image compression during training, which wasn't configurable before.

## Why?

Enabling probability control over image compression is crucial for augmenting datasets more effectively, giving developers more flexibility in generating augmented data. T
## How?

The implementation adds an additional parameter to the existing yolo pipeline. The probability of applying the transformation is passed as an argument, which is set by the user. This change ensures backward compatibility, keeping the default behavior unchanged if the probability is not specified (by default 0.9).

## Testing
 
the updates seems to work as expected when passing different values

- **Compression Disabled:** When passing the value `0`, the image compression is disabled, as verified in the logs where no compression is applied.

![Screenshot from 2024-10-08 17-25-11](https://github.com/user-attachments/assets/7b692906-413d-472e-8af8-7cd07d4ff5f8)

- **Compression Enabled:** When passing any value greater than `0`, the compression is enabled, and this can be seen in the training logs.

![Screenshot from 2024-10-08 17-28-31](https://github.com/user-attachments/assets/66990a73-1afa-43c3-9900-7eb949c7937b)

2024-10-09 07:37 UTC, kevinconka commented
Let's please improve the PR description, aim for simple and concise information:
- The title is super long
- The _what_ should be straightforward: new parameter added to `train.py`
- the _why_ is very generic, the real reason you know it. There was no way to control the compression parameters from the train script.
- In the _how_, you can mention the parameter name and an example usage.
- for the _tests_: which command did you run? an output has virtually no meaning when I don't know the input.

2024-10-09 07:49 UTC, kevinconka requested changes
Clean implementation. Minor details + question about implementation on `val.py` 🤔

2024-10-09 07:49 UTC, kevinconka commented on train.py
perhaps super picky, but when I read the code, it is not explicit that `image_compression` refers to a probability between 0.0 and 1.0; instead I think of it as a boolean. Maybe `image_compression_prob` or `im_compression_prob` (for slightly shorter) could make it more explicit.

2024-10-09 07:49 UTC, kevinconka commented on utils/augmentations.py
same observation here, since [ImageCompression](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.ImageCompression) has multiple arguments, it is not clear from the name what `image_compression` means. 
Someone who might know about Albumentations might think: is it quality? enable/disable? type of compression?

2024-10-09 07:49 UTC, kevinconka commented on val.py
why do we add image compression augmentation probability for validation?

2024-10-09 16:24 UTC, hichem-sea commented on train.py
done

2024-10-09 16:24 UTC, hichem-sea commented on utils/augmentations.py
done

2024-10-09 16:24 UTC, hichem-sea commented on val.py
done, removed from the validation

2024-10-10 08:36 UTC, kevinconka approved these changes
LGTM

2024-10-10 10:16 UTC, merged